/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CasterGatePanel.java
 *
 * Created on Aug 23, 2010, 6:44:11 PM
 */

package root;

import javax.swing.SpinnerNumberModel; 

/**
 *
 * @author Administrator
 */
public class CasterGatePanel extends javax.swing.JPanel {

    CasterDataModel CDM;

    /** Creates new form CasterGatePanel */

    CasterGatePanel(CasterDataModel mwf) {
        initComponents();
        CDM = mwf;
        GateTable.setModel(CDM.GetMoongateDefaultTableModel());
        //Timer t = new Timer()
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FutureGateSpinner = new javax.swing.JSpinner(new SpinnerNumberModel(6,0,20,1));
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        GateTable = new javax.swing.JTable();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        FutureGateSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                FutureGateSpinnerStateChanged(evt);
            }
        });

        jLabel1.setText("# Future Gates");

        GateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(GateTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FutureGateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(FutureGateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FutureGateSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_FutureGateSpinnerStateChanged
        CDM.SetNumberOfMoongatesShown((Integer)FutureGateSpinner.getValue());
        UpdateTable();
    }//GEN-LAST:event_FutureGateSpinnerStateChanged

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        if (this.getWidth() <= 144) //Hardcoded width of the panel at absolute minimum
        {
            this.jLabel1.setVisible(false);
        } else {
            this.jLabel1.setVisible(true);
        }
    }//GEN-LAST:event_formComponentResized


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner FutureGateSpinner;
    private javax.swing.JTable GateTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables


    private void UpdateTable()
    {
        this.GateTable.setModel(CDM.GetMoongateDefaultTableModel());
    }

}
